- hosts: all
  sudo: yes
  tasks:
      - name: Ensure dependencies are installed.
        apt: pkg=curl state=installed

      - name: Add Jenkins apt repository key.
        apt_key:
          url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
          state: present

      - name: Add Jenkins apt repository.
        apt_repository:
          repo: "deb http://pkg.jenkins-ci.org/debian binary/"
          state: present
          update_cache: yes

      - name: Ensure Jenkins is installed.
        apt: pkg=jenkins state=installed

      - name: Ensure Jenkins-cli is installed.
        apt: pkg=jenkins-cli state=installed

      - name: Ensure Jenkins is running
        action: service name=jenkins state=started

      - name: Create a job with Jenkins-cli using an existing jobs xml
        shell: 'jenkins-cli -s http://localhost:8080 create-job test < /vagrant/jobs/test.xml'
